
--增加VIP价格字段（乐园）@zhongyidong
ALTER TABLE `act_spec` ADD COLUMN `VIP_PRICES` TEXT NULL DEFAULT NULL  AFTER `LIMITS` ;
ALTER TABLE `act_stock` ADD COLUMN `HIGH_VIP_PRICE` INT(8) NULL DEFAULT 0 COMMENT 'VIP价格-最高价'  AFTER `LOW_PRICE` , 
	ADD COLUMN `LOW_VIP_PRICE` INT(8) NULL DEFAULT 0 COMMENT 'VIP价格-最低价'  AFTER `HIGH_VIP_PRICE` ;
	
--增加VIP价格字段（酷袋）@zhongyidong
ALTER TABLE `kd_p_stock_detail` ADD COLUMN `VIP_PRICE` INT(11) NULL COMMENT 'vip价格'  AFTER `PRICE` ;
ALTER TABLE `kd_p_product` ADD COLUMN `LOW_VIP_PRICE` INT(11) NULL COMMENT 'vip价格最低价'  AFTER `HIGH_PRICE` , 
	ADD COLUMN `HIGH_VIP_PRICE` INT(11) NULL COMMENT 'vip价格最高价'  AFTER `LOW_VIP_PRICE` , 
	CHANGE COLUMN `IS_DELETED` `IS_DELETED` VARCHAR(45) NULL DEFAULT '0' COMMENT '是否删除。0-未删除，1-已删除'  AFTER `VIP` ;



